plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.2'
    id 'io.spring.dependency-management' version '1.1.7'
}

configurations {
    management {
        visible = false
        canBeConsumed = false
        canBeResolved = false
    }
}
configurations.compileClasspath.extendsFrom(configurations.management)
configurations.runtimeClasspath.extendsFrom(configurations.management)
configurations.testCompileClasspath.extendsFrom(configurations.management)
configurations.testRuntimeClasspath.extendsFrom(configurations.management)

repositories {
    mavenCentral()
}

dependencies {
    management platform('org.testcontainers:testcontainers-bom:1.21.4')
    testImplementation "org.testcontainers:testcontainers"
}
