plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

configurations {
    management {
        visible = false
        canBeConsumed = false
        canBeResolved = false
    }
}
configurations.compileClasspath.extendsFrom(configurations.management)
configurations.runtimeClasspath.extendsFrom(configurations.management)
configurations.testCompileClasspath.extendsFrom(configurations.management)
configurations.testRuntimeClasspath.extendsFrom(configurations.management)

repositories {
    mavenCentral()
    maven { url 'https://repo.spring.io/snapshot' }
    maven { url 'https://repo.spring.io/milestone' }
}

dependencies {
    management platform(libs.org.testcontainers.testcontainers.bom)
    testImplementation "org.testcontainers:testcontainers"
}
