plugins {
    id "java-gradle-plugin"
    id "java"
    id "groovy"
}

gradlePlugin {
    plugins {
        managementConfiguration {
            id = "io.spring.convention.management-configuration"
            implementationClass = "io.spring.gradle.convention.ManagementConfigurationPlugin"
        }
    }
}


dependencies {
    implementation localGroovy()

}

