= Spring Session - Mongo Repositories
Jakub Kubrynski, Vedran Pavić
:toc:

This guide describes how to use Spring Session to transparently leverage Mongo to back a web application's `HttpSession` when using Spring Boot.

NOTE: The completed guide can be found in the <<mongo-sample, mongo sample application>>.

== Updating Dependencies
Before you use Spring Session, you must ensure to update your dependencies.
We assume you are working with a working Spring Boot web application.
If you are using Maven, ensure to add the following dependencies:

.pom.xml
[source,xml]
[subs="verbatim,attributes"]
----
<dependencies>
	<!-- ... -->

	<dependency>
		<groupId>org.springframework.session</groupId>
		<artifactId>spring-session-data-mongo</artifactId>
	</dependency>
</dependencies>
----

Spring Boot provides dependency management for Spring Session modules, so there's no need to explicitly declare dependency version.

[[mongo-spring-configuration]]
== Spring Boot Configuration

// tag::config[]
After adding the required dependencies, we can create our Spring Boot configuration.
Thanks to first-class auto configuration support, setting up Spring Session backed by Mongo is as simple as adding a single configuration property to your `application.properties`:

.src/main/resources/application.properties
----
spring.session.store-type=mongo
----

Under the hood, Spring Boot will apply configuration that is equivalent to manually adding `@EnableMongoHttpSession` annotation.
This creates a Spring Bean with the name of `springSessionRepositoryFilter` that implements Filter.
The filter is what is in charge of replacing the `HttpSession` implementation to be backed by Spring Session.

In addition to that, you have to add the following Spring Configuration:

[source,java]
----
include::{samples-dir}boot/mongo/src/main/java/sample/config/SessionConfig.java[tags=class]
----

<1> We explicitly configure `JdkMongoSessionConverter` since Spring Security's objects cannot be automatically persisted using Jackson (the default if Jackson is on the classpath).

Further customization is possible using `application.properties`:

.src/main/resources/application.properties
----
server.session.timeout= # Session timeout in seconds.
spring.session.mongo.collection-name=sessions # Collection name used to store sessions.
----

For more information, refer to http://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#boot-features-session[Spring Session] portion of the Spring Boot documentation.

// end::config[]

[[boot-mongo-configuration]]
== Configuring the Mongo Connection

Spring Boot automatically creates a `MongoClient` that connects Spring Session to a Mongo Server on localhost on port 27017 (default port).
In a production environment you need to ensure to update your configuration to point to your Mongo server.
For example, you can include the following in your *application.properties*

.src/main/resources/application.properties
----
spring.data.mongodb.host=mongo-srv
spring.data.mongodb.port=27018
spring.data.mongodb.database=prod
----

For more information, refer to http://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#boot-features-connecting-to-mongodb[Connecting to MongoDB] portion of the Spring Boot documentation.

[[boot-servlet-configuration]]
== Servlet Container Initialization

Our <<boot-spring-configuration,Spring Boot Configuration>> created a Spring Bean named `springSessionRepositoryFilter` that implements `Filter`.
The `springSessionRepositoryFilter` bean is responsible for replacing the `HttpSession` with a custom implementation that is backed by Spring Session.

In order for our `Filter` to do its magic, Spring needs to load our `Config` class.
Last we need to ensure that our Servlet Container (i.e. Tomcat) uses our `springSessionRepositoryFilter` for every request.
Fortunately, Spring Boot takes care of both of these steps for us.

[[mongo-sample]]
== Mongo Sample Application

The Mongo Sample Application demonstrates how to use Spring Session to transparently leverage Mongo to back a web application's `HttpSession` when using Spring Boot.

[[mongo-running]]
=== Running the Mongo Sample Application

You can run the sample by obtaining the {download-url}[source code] and invoking the following command:

----
$ ./gradlew :samples:mongo:bootRun
----

You should now be able to access the application at http://localhost:8080/

[[boot-explore]]
=== Exploring the security Sample Application

Try using the application. Enter the following to log in:

* **Username** _user_
* **Password** _password_

Now click the **Login** button.
You should now see a message indicating your are logged in with the user entered previously.
The user's information is stored in Mongo rather than Tomcat's `HttpSession` implementation.

[[mongo-how]]
=== How does it work?

Instead of using Tomcat's `HttpSession`, we are actually persisting the values in Mongo.
Spring Session replaces the `HttpSession` with an implementation that is backed by Mongo.
When Spring Security's `SecurityContextPersistenceFilter` saves the `SecurityContext` to the `HttpSession` it is then persisted into Mongo.

When a new `HttpSession` is created, Spring Session creates a cookie named SESSION in your browser that contains the id of your session.
Go ahead and view the cookies (click for help with https://developer.chrome.com/devtools/docs/resources#cookies[Chrome] or https://getfirebug.com/wiki/index.php/Cookies_Panel#Cookies_List[Firefox]).

If you like, you can easily inspect the session using mongo client. For example, on a Linux based system you can type:

[NOTE]
====
The sample application uses an embedded MongoDB instance that listens on a randomly allocated port.
The port used by embedded MongoDB together with exact command to connect to it is logged during application startup.
====

	$ mongo --port ...
	> use test
	> db.sessions.find().pretty()

Alternatively, you can also delete the explicit key. Enter the following into your terminal ensuring to replace `60f17293-839b-477c-bb92-07a9c3658843` with the value of your SESSION cookie:

	> db.sessions.remove({"_id":"60f17293-839b-477c-bb92-07a9c3658843"})

Now visit the application at http://localhost:8080/ and observe that we are no longer authenticated.
